"use client";

import { useDocumentStore } from "@/store/document";

export function ReviewSidebar() {
  const document = useDocumentStore((s) => s.document);

  if (!document) return null;

  const blocks = document.blocks;
  const total = blocks.length;
  const approved = blocks.filter((b) => b.review?.status === "approved" || b.review?.status === "pre_approved").length;
  const flagged = blocks.filter((b) => b.review?.status === "flagged").length;
  const pending = total - approved - flagged;
  const progress = total > 0 ? (approved / total) * 100 : 0;

  const { meta } = document;

  return (
    <aside className="w-72 flex-shrink-0 p-4 border-l border-gray-200 dark:border-gray-700 overflow-y-auto" aria-label="Review sidebar">
      <h2 className="text-lg font-bold mb-4">Review Progress</h2>

      {/* Progress bar */}
      <div className="mb-4">
        <div className="flex justify-between text-sm mb-1">
          <span>Progress</span>
          <span>{progress.toFixed(0)}%</span>
        </div>
        <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-3" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}>
          <div
            className="bg-green-500 h-3 rounded-full transition-all"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      {/* Counts */}
      <div className="space-y-2 mb-6">
        <div className="flex justify-between text-sm">
          <span className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-green-500" aria-hidden="true" />
            Approved
          </span>
          <span className="font-mono">{approved}</span>
        </div>
        <div className="flex justify-between text-sm">
          <span className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-yellow-500" aria-hidden="true" />
            Pending
          </span>
          <span className="font-mono">{pending}</span>
        </div>
        <div className="flex justify-between text-sm">
          <span className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-red-500" aria-hidden="true" />
            Flagged
          </span>
          <span className="font-mono">{flagged}</span>
        </div>
      </div>

      {/* Provenance */}
      <div className="mb-6">
        <h3 className="text-sm font-semibold mb-2 text-gray-500 dark:text-gray-400 uppercase tracking-wide">Provenance</h3>
        <dl className="text-sm space-y-1">
          <div className="flex justify-between">
            <dt className="text-gray-500 dark:text-gray-400">Generated by</dt>
            <dd className="font-mono text-xs">{meta.provenance.generated_by}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-gray-500 dark:text-gray-400">Reviewed by</dt>
            <dd className="font-mono text-xs">{meta.provenance.reviewed_by}</dd>
          </div>
        </dl>
      </div>

      {/* Variables */}
      {Object.keys(meta.variables).length > 0 && (
        <div>
          <h3 className="text-sm font-semibold mb-2 text-gray-500 dark:text-gray-400 uppercase tracking-wide">Variables</h3>
          <dl className="text-xs space-y-1 font-mono">
            {Object.entries(meta.variables).map(([key, value]) => (
              <div key={key} className="flex justify-between gap-2">
                <dt className="text-gray-500 dark:text-gray-400 truncate">${key}</dt>
                <dd className="truncate">{value}</dd>
              </div>
            ))}
          </dl>
        </div>
      )}
    </aside>
  );
}
